export const AMBIENCE_PRESETS = [
  {
    id: 'cozy-study',
    emoji: '📚',
    title: 'Cozy Study',
    mood: 'Lecture calme',
    sceneId: 'moon-girl',
    streamId: 'X4VbdwhkE10',
    focusTime: 25,
    shortBreakTime: 5,
  },
  {
    id: 'jazzy-flow',
    emoji: '🐾',
    title: 'Jazzy Flow',
    mood: 'Travail souple',
    sceneId: 'train-girl',
    streamId: '5yx6BWlEVcY',
    focusTime: 45,
    shortBreakTime: 10,
  },
  {
    id: 'rainy-deep',
    emoji: '🌧️',
    title: 'Rainy Deep',
    mood: 'Focus profond',
    sceneId: 'montaign-work',
    streamId: '7hfTa8nXKk8',
    focusTime: 50,
    shortBreakTime: 10,
  },
  {
    id: 'nature-reset',
    emoji: '🌿',
    title: 'Nature Reset',
    mood: 'Session legere',
    sceneId: 'nature-work',
    streamId: 'X4VbdwhkE10',
    focusTime: 20,
    shortBreakTime: 5,
  },
];
